### ISSUE TITLE
doesn't work in chrome 67.0.3396.87

### ISSUE THREAD

**Issue by ghost** [PhilGrayson/chrome-csp-disable#10]
i downloaded your extension and installed it and it worked properly in chrome 63.0.3239.132, but now when i updated to chrome 67.0.3396.87, it doesn't work.

i opened developers tools and i see security policy header present there, and it also doesn't allow me to execute inline events anymore

can you please take a look and confirm the issue and let me know if i can somehow help on resolving the issue. thanks

**Comment by PhilGrayson** [comment]
Blah, sorry for never responding. I'm going to close this since we're up to Chrome 81.x and it seems to work for me ¯\_(ツ)_/¯
