### ISSUE TITLE
Please put it on the edge store, need account synchronization extension 

### ISSUE THREAD

**Issue by aogg** [PhilGrayson/chrome-csp-disable#17]
https://microsoftedge.microsoft.com/addons/search/csp?hl=zh-CN

Edge will not synchronize the expansion of non-edge stores

**Comment by nagachaitanyalokam** [comment]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by PhilGrayson** [comment]
This extension is on the Edge store now
https://microsoftedge.microsoft.com/addons/detail/disable-contentsecurity/ecmfamimnofkleckfamjbphegacljmbp

I'm not clear what "account synchronization extension" and "synchronize the expansion of non-edge stores" means, but hopefully having the extension published now is good enough.
