### ISSUE TITLE
Does this work in HTTPS?

### ISSUE THREAD

**Issue by gberger** [PhilGrayson/chrome-csp-disable#2]

**Comment by PhilGrayson** [comment]
sorry for the late reply, I should really review my Github notifications.

I believe this works on HTTPS sites. Pull request #1 added that feature. I've tested it on a HTTPS site with CSP violations. When the extension is active the violations disappear.

If you have an example URL where you think the extension isn't working correctly I'll gladly investigate further.

**Comment by gberger** [comment]
I couldn't make it work on web.whatsapp.com

**Comment by cael-gomes** [comment]
+1, couldn't make it work on https://web.whatsapp.com/
