### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cameronelliott** [PhilGrayson/chrome-csp-disable#21]
This is fantastic!  Thank you for making it!!

What is the license?

If your open to it, can I suggest the MIT license or public domain?
https://choosealicense.com/licenses/mit/
https://choosealicense.com/licenses/unlicense/

Thanks again, this saved my life!

**Comment by PhilGrayson** [comment]
Hey, thanks for the kind words, and licensing suggestions.

The Unlicense seems fine, knock yourself out!

Take care,
Phil
