### ISSUE TITLE
Does the plugin work in chrome 49

### ISSUE THREAD

**Issue by AndersBillLinden** [PhilGrayson/chrome-csp-disable#3]
I am using Version 49.0.2623.112 m. If I try to access the contentDocument property of an iframe element where the iframes current location is on another server I am getting:

Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:51904" from accessing a frame with origin "http://10.200.200.211". Protocols, domains, and ports must match.

I have toggled the button in the add-on bar so it have had both appearences doing this.

Did I misunderstand the functionatlity of the plugin or is it not keeping up with newer browsers?

**Comment by PhilGrayson** [comment]
Hi,

It sounds like you are triggering 'Same-origin policy' violations.

> Under the policy, a web browser permits scripts contained in a first web page to access data in a second web page, but only if both web pages have the same _origin_.
> This policy prevents a malicious script on one page from obtaining access to sensitive data on another web page through that page's Document Object Model.
> https://en.wikipedia.org/wiki/Same-origin_policy

I recommend looking at either [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) or [document.domain](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Changing_origin) when dealing with iframes.

Content-Security-Policy is a way for site owners to prevent execution of resources from untrusted domain. This helps protect (but doesn't prevent) visitors from malicious scripts.

**Comment by AndersBillLinden** [comment]
Ok, thanks!
