### ISSUE TITLE
The extension is turned on by default

### ISSUE THREAD

**Issue by Mondane** [PhilGrayson/chrome-csp-disable#5]
I've installed the plugin and it turns out by default it will disable the content-security-policy on my sites. Could it be made so that the default behavior is to do nothing so the browser defaults are intact? Now I have to disable the extension when I'm finished doing my stuff.

Or add the 'whitelist' as mentioned in #4

**Comment by PhilGrayson** [comment]
I noticed the default state of the plugin is a little screwy, almost like the enabled boolean isn't initialised correctly.

The plugin should be default off.

**Comment by PhilGrayson** [comment]
I'll make an update to set Content Security Policy enabled by default when you install this plugin.

I'll also fix the icon state being inconsistent on first usage.

**Comment by PhilGrayson** [comment]
I've pushed v1.0.5 of this extension to the Google Web Store. You'll get it when you next update your extensions.

Cheers for the feedback.
