### ISSUE TITLE
Wrong boolean in if statement

### ISSUE THREAD

**Issue by ghost** [PhilGrayson/chrome-csp-disable#8]
At line 4 in background.js, shouldn't the statement

```JavaScript
if(!isCSPDisabled)
```

be replaced with the following statement?

```JavaScript
if(isCSPDisabled)
```

I tried your script and it doesn't disable CSP. But, when I changed **!isCSPDisabled** to **isCSPDisabled** it works properly. It seems that you're returning from the function if CSP is not disabled, which doesn't make any sense.

**Comment by PhilGrayson** [comment]
It makes sense. If CSP is not disabled, do not alter the HTTP response headers.

I suspect you didn't click the extension icon to 'enable' the disabling of CSP.

The purpose of 'enabling' the extension by clicking the icon is so users are less likely to forget to re-enable CSP.

**Comment by ghost** [comment]
Oh, my bad, sorry. I didn't even read the whole script, instead I just removed UI part and embedded the rest in my old extension, which of course yielded in **isCSPDisabled** always being false. I'm closing this issue as invalid.
