### ISSUE TITLE
CSP Errors with redirects

### ISSUE THREAD

**Issue by dougscher** [PhilGrayson/chrome-csp-disable#9]
I get this error when a script is redirected to a different site using a redirector extension (switcharoo):
Refused to load the script ... because it violates the following Content Security Policy directive: "script-src 'self'  ... https: 'unsafe-inline' 'unsafe-eval'".

All over https, the redirected site is on http.
The failing site has an intense CSP policy in a Content-Security-Policy meta tag.
I do this kinds of redirection all the time with many other https sites without any CSP errors using your extension.

**Comment by PhilGrayson** [comment]
Hi there, I'm really sorry to have ignored your message.

Are you still interested in getting help for this issue? If so, can you share a way to replicate the issue?

**Comment by dougscher** [comment]
I switched the local sites to https, no longer having an issue - Thanks for following up
